// actionTypes.js
export const FETCH_OTHERSTATS = 'FETCH_OTHERSTATS';
export const FETCH_OTHERSTATS_FAIL = 'FETCH_OTHERSTATS_FAIL';

export const FETCH_SALES = 'FETCH_SALES';
export const FETCH_SALES_FAIL = 'FETCH_SALES_FAIL';

export const FETCH_AUTHUSER = 'FETCH_AUTHUSER';
export const FETCH_AUTHUSER_FAIL = 'FETCH_AUTHUSER_FAIL';